apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - generate-ceph.sealed_secret.yaml
  - benji-config.sealed_secret.yaml
  - benji.yaml
  - push-gateway.yaml
  - cron-jobs.yaml
  - zrepl.yaml
  