---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-ceph-mon
  namespace: backup-system
spec:
  encryptedData:
    ceph-secret: AgCy6Lyquck+7zi5N5xsfSFGcGFdo2kZIsEGyV9UzukshMT4mzUHcfbdkCaVBy8SD2vZCuF5A5/EbQhhfMCZtzDVYjW+1IGkHXBLPO8mAKgtMqeobWcqCT3AqfmM5dplsqZXfWjUCvG3AP5IQg6RBIKp4R4cLf2wbwlJ0nsNdQNU8kPoP49XZByh1VpL7PUaY9ZHu1sdilZgSOtzDR1erxHvVGtf37SeYJ27xE95wKpNu2ip55JiShBzAi4AdjGpz8tcvv4zhvyYqAR5nNEnbUhBcfrKhhMpPnpuEdanFJHjHw0bmeGNTxvpITLhkxTmrT+8vmSDdFzp6Ht0ApmZPYXqfAgDQUS+bG4Mn3ygP6Pj06U184VUWc8syBsRf1FqTD4q84Gp62I0QyepBZql30wx0Tz0CclEpSRLx01if9OnlQxNCOaLKhtCEkHYKbHtbvbk2yc2JdMOeSDWJs0mLsS5kZA3zgTIWThBAm/2OZAXqv+dZYtjQ6Smzd52WVkHPRUR+EqAv5JugOADnU6CYvl4G0N+kyu6+B63K3M/4pQufcuSFR4bUR+/jjexpzF+LFDuyJTV21Rx6roFzXgNOjgN502JQwMG8rZ3EZm9EA5gddqfzSPDpvwZFqVQVMBja7bhzVjzOz0laetXVVXgyAg3Lerij5y9SAk6Y9t6HKqlBqN6usiTS9GOi8lNvKw4O72agXE+Q+Xfv+JQ6XIjQnyVkPZfnNON15oLpgUVhfaMuR4fPpx+zZlZY8yWmleCT4t0l3QWEp6y8Q==
    ceph-username: AgCCtxDgaeYUQFIXry79IoZX7ApnHx/oSwG8CvQqIbdmNZTb6PNF1MejhcplYm/pFhH7+kiEvzrcRcYRV/ytVDySVbHQ3hvOpoIq47S0ppCsDTKdxyc3Ac0JBAV1RpmpYN6HearlvY4DbtTQjYmF7rvtrBKnyPaYPyDHL/APHt2ULgcbfdOR9T2TWBI0DOUWtVxcPzl68tetdyEXGFZuiTGaxrdYOVFOI8lKY6XcuQzdb6zBS/g49wBp7DhRwFh4Wp1nuvpHXvgDBWazD/2QIExAXibIKCYwvnntO2ZCBHOU6Bdi6jAUbEfltiJC6GoHCOfhbqvlu3pPMzqNT4P+Nhy0Dpl1u8I3w8zlkUf2hKOO0Dlzm/sVKY4nRaihQzE8sg1q6cbPtB3FwFMQKLKk0JznoSNySXSLMoFIrMTUxVEGiOC7kwTjhxNewirWXz9UB4t+FYilM1P0BTim1t8r+ONcgdc2I7pkQyI9syFSuyv7CtP2rAtqc+Lz72W2pP9ruFoRNNVGsSkXt/uDHRBTpwS42P3Frcn2FzJACezbbyvX2l48GlPhuMcfpY2+zyLqcE6/pCxj8UGbyywXSm5FnOrC1WMyB8qiabLfICwKpCNexmzksuJnxLLCbPr4LJqlJRaouZovTSOygZr8abhb1CCghmwjorZcfyDFQV5XOJlU1BWvMqRlAMOUGisTrR8MnhErdw95bHeY7bWavYe6ssR0
  template:
    metadata:
      creationTimestamp: null
      name: rook-ceph-mon
      namespace: backup-system
