---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-ceph-mon
  namespace: backup-system
spec:
  encryptedData:
    ceph-secret: AgBgucfchgFMx/oCEvoqfC+2UaBtygyjuensvAuOWVgXDDD8Q6nYnE+PhxBsV2hO3HMqYkfdSi8ufKd0kNWfFyZEjtvc6nl0DEp+BCx8ib2oI1vijznDjosklM0ZlMCCmd+zr7xBeISbi3ewMRLNWp4fyfPgl5fC6k0abQglEdPvl0s8h3OFKUqPgcwgJLAvqiCtQiNW9eNQAP0BJHt3jZRnb5ysgVbt7WCAsv7X93pDrzWDq7abIJe16AYlAorw7KougoavMozAQpBCfOVmVYg1wX4Jzq5Utor5owH2b4Rv81T3F/ARjW5mgfI4HAHHLmOqzxSwr4xOwOuYHnNl54eBeds0x4HSSIpnc5sjDO0EwDFDltOrGoJ+AKBGwtRwqFYp1/oF47jUJL6ksrnLb6iLU6cS30Znv/zoNJmBdexQE3AqL3s6NfRVaxhjk/ZKXjEwaj9D9by4vVGFRkKbxPjDpjaAVEH+Ee4nahCBRDp+lbbCRvtPHaAMcKrAJSzmr82+hKFdxmeHDEB0eizyktNkBvSi4zyVfT/G5HpwGv9lvH+UYLnyBe361NWWkVyruZJJ0nKw5g64qug8I+EM969zD0xQK46MbxBtFj0LrialtJpQKQc5lZGTWGdsQta6w20+qZB5nV/Jj8Yq4Rhsgml4Jx0To515Io/kfy2nHqNLilBLwEzx2cLauHLKNIZaCoEw04yFDRUd/vpd3/RYbn7wuk/K0jozYgmAjcRt35aSh5bZon0JDILLdUvSYJLENqQYmugw3Cwiqg==
    ceph-username: AgBLB0UB9Uq5d3HA5IEU5aBbX2B5RNwnUntLf63XnW6KAkXGW5AEWwt+ap1ISmVzhWTz6QdAJnYIsvZ79P4pphNg4y7Mp1V3DlRJSGfvAN5GoktaCi62ZeFL3oiAVXX+kjsrcUAahFyPkny6h+Lw65TgQOpB3qDQ6XJ0hSObBAsVLr73CCEO3uB3QhufKKo43MCRZxle/hh5rMHG4hbhFIkQB+YQ8EE4yy/WR6B8FEAZXK4NWKtyLHAJdMfYrgG81gkBWr5NTK1LcoFRckO2li+2QFVE2B+CkhEcvCMEsTl9mQtel9o5PpSI9z9jIkMir6KLfYkvhCcVZCZLTjOB0fTDU1ux/eih574J+sT0SRslzve65blGt2uMYG6d2NyYRM7YAT39/Ktenk3umZW3SlTA+vqVqD+crNI7YcKJ5vDFoS0i/GyV32pybxCGTcKv2LkhivHl1B3E2F/ZwgL+0jlZAqEKecx+UP1cjfOSi6Fm5XTmGgtksAukiOh6oNFGWoNojwexqC4gsmhSRaNbEjit6S+ogrOFEXpS01KQwmca/40wei84P7fjnjMkCxi70hiNt0AKH/CNBCEXN01feKjbQ/dfvHuqGnIt8WTvTgU/siQBUxWTFvLd+wz9kJZiBbk5eTuXvVkwNxosspuxMx9wcwLHO5fuxvlu3pp7KCX9ZXPneLkDY7g8uBry+BWlYC5b2dgdwOORUZGYjAOFfqG9
  template:
    metadata:
      creationTimestamp: null
      name: rook-ceph-mon
      namespace: backup-system
