---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-ceph-mon
  namespace: backup-system
spec:
  encryptedData:
    ceph-secret: AgCl9DkWdViUO12xVEPKjCEL5uvjul2LosZLlmFiIEFoWghcloFPrL7sBdjQPAb/LiiqmsRCC0Jy6mkIZey/ToUowAnsE6dFbxc4OomX1bDiaQTgCrliH337QebLA38moKB4gyoJWZG510Sk4CMeTSwRASW5LxS7tPGHl5iMyO+vgbpJl+zpStYioPurweuCBSOOhP/Zi7k3F9WFH7ipfutwPiE0UfO0awY6SVf4DTsLVAPdhLXTjJp+SCP2dyKBlbtx7L8/qeXmjZlrb8Bx3eQCVx+ANueMKX564V/XquATJxLQEjRfbcYE+JSIWamfRUtJUlbswrdsQYN1g+2V4ecsMnUmqbqa2v7N5JOrj4bW7OyLhUtcsUFA7+KiF1/3xZPHiAzEjmT7tejkCphITK5G9joMsYposIQLwJfHTFitrtUq8kkah+r0bTgiCws+0QYrTL8t6074ysKalhFc2ZAH7Bhst548w18ItZf9ixolXO9kPbImnyoDD6bqyPxcIvzSOwVn8gmRO6yXK/pPq+7Dzusj/x/Z7zK1S+oTNT0nttdJgJ2xcATNdc819d+3PUbPArruiCNvzMAzLxf44Q5GtAltsc1RqmNKevWnciccrj/ZNGHs5UlmvBHoMthaHs1tzfG2+Gx+2UyLZX6bwrvyFQRnoLXhYOhYxAyLpPT4yEzuwU18eMjCVMo4ML5No47/00r2kdVLr0VAGDOt1AGcxWlRD7dQy6REdADd+/f+FM8T6uj0/1yemmvVp5a/vdxN9JxB3uIOnA==
    ceph-username: AgCs3NbQltdX2MN+qKEr4I3dYVPvzy1nhrm+Qf3wozAX4bIKGakslQ4rosoGd8UF8oTngrMN2ahB758LmQ+xkjqR6pmnAJ158IaBP0gb6EaiRZkJGPgg1etxd8yvXXv1k+6u2a80Aq9wBSPQorroCrAmfCAM7m6Yjq0+GfLVDa2X6zHTuCi7Gd7QDNsVvG9xzYORrShOlGg9t3+ZCLMisnZX6hNG9EuTx1PdanpD/p9GCGgtYYDV4MQt6dcj5GY0FnqaLSDJYgGTG4bs1bC4W5nTN1Ga/e/0uvl5E3n4rrDH+4tOGATGT4YVeGEgkVRhbjjPjMcOTbkQVZb7s4acXStpTYYWWpIJTCHutAe4eMIjEpS3DOShgbfusckG2n+QfP2Dms0gyJDFIGWA3sJCeDkQ28+Pi0NpiTTQBmpulYObE/wJD3ffEscNCqAm4yO5LEidu7PhG1H0r6kO+QXl7cmqsUxV5ja5BB0KO2DZ20bAxHJAZvxFg6wCxcagQ6HR7PIfJUdvc0F2+Xo/1BtPhLIwc28JC8YG1o8qP2R0BiltllBNV1dw96rKGUas3+DguSU8yWm0oaSxjr/PAPW8v49bTxK1cVzrkPrJnmEJqApOVdf6x+LHtQ5uNTN2hU/jbgJSM7SXpmzvLznWqH0IwO9PvPN5r1T2QmRacMvDTO5aIbSUJNczm4TJfkbNr821WdGGtqDDe0ar/z7oev47biKh
  template:
    metadata:
      creationTimestamp: null
      name: rook-ceph-mon
      namespace: backup-system
