---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rook-ceph-mon
  namespace: backup-system
spec:
  encryptedData:
    ceph-secret: AgBhJMsAwBp2TdTjmIznYsAlGYD/u+TJ/GxpAARtZrNcyUfNX6Cavy1DQy9kXQHsWwoNoczuKoFcd41Ao2KVYT1InEl0c9C2Gk/8yXtX1TPY+ad6KHg+ffZVxozT7q3hEqQCoR0oLyx7ePX9esIP9w3Xctoa2myMO2x0BIhJJVcwf8IUi4zeufsynqtT8U246TuJq2ZaCPGADETva8pYda6nu8PdnSLjw61Itli+VxFb8vzZFc5k38isyHHXKNm+pgIqSrP+DBPh2MjF3mUK4rky3ffMvY5MWH2u6nbjJgZGz6KjGLZw9BWOZjCVn46ZHuyuCHHe2+LRdaUh9NmNswX3A0OfXKbZerZvAcBEf7vaNP2F80zMftiFpJdpQwgZmtFt13B16WtMQxVk2kMsOLpC5PVk45gap1xr/Thy35UcQlpNgKFg+OcEdDQRDY+laQ+Uz5W1rLz+LVrpuFazItzGAI7BPF6juKNac9dbqc1vMz2dtufxi3xZfXLXhAsomYFwUrJOg+5m5BHnEpy9HMimYbzi05CD88F7soF/Ia66KFVWp7Vq1xaTBuMBbA0p7IyvpP94ZjNYTHhEOtoT8uWHBZmL+qu4dW6vnKtnp7a+E3qLD4hi/7xJuc5WX+paeLtm44JCqRur/ioViU4kysQ4BCIk3o0iZmW4T4I0R45aIDn4KjhQJSo/nkdyhl+v+aw8NxPhcEVa1lKpvqcY+XVeozDH1qvhEvz+8H7qlVlkf5SphRSL18IK4jcPsOOZR1wJK7EO4KkTEQ==
    ceph-username: AgBRzfQlY+qnOlm+v/5Tn9goL0DC3w/pY3KGmg0ozJD/mzHunQa73ZHtJuylNveCU4NyhB9/bQaq26Se7rAp5aDuRSHv83jlmoqxvLI85tq0IlWc00TpjZNAM7iaZpYvl36lGIKuvfyQVI9nvJmu53jQo31Q1ctkUXvcrcnkFxjJLjKl2trXZav/3g7TiZCaL6bYCmLzgTI9t4/N6YPLTR5rAyzgjdI6mm6snSqMRIc/q5x58/W01Y9b2X3j1UzleI1gwgKY86piKoXv4H1816FujzTBoyaC9Q5JzoZklHnzzaUVQm6LeGxjlZKmIpYOjEMGZO/0iyFpKkRDSvLSYgobFBmMGNDVZhHl7pdZaGqxNjylt5pN+oAiaF9YY7bmTMF5kxa2Vddwn6s8rq57gk/Bz1FXYh1gawggwG5rPsuqOkH8ynri1lCwuhhaWDns0cCirZ1xDK0fdGwvTnO7yUrmqsqisq/lNT5xf42bjmBrpIhv1HJUDp6TE8Mx3NLtf4HTSz3zexFNmoQe0ms/s+bov4HOypz7verdUdlFd0kcSVgpubKK41VpYspVGMJ7L4dExw7yatC6gaA3LMm3VXJQKBlENM3z44f78PPbHTVNP9esDa7a1ryg0o88zDR2fAtSr5f/gI3VP2t0e+EWnet4TbMrxuCOUulUbH5hpkHlAY66tSLNZPzEg93qxh6F0DMoW7vKxAmQlX5hgUaN+wjv
  template:
    metadata:
      creationTimestamp: null
      name: rook-ceph-mon
      namespace: backup-system
