apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zmod-telegram-timelapse-data
  namespace: zmod-telegram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zmod-telegram-timelapse-finished
  namespace: zmod-telegram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zmod-telegram-logs
  namespace: zmod-telegram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
