apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vw-data-ceph
  namespace: vaultwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: rook-ceph-block