apiVersion: v1
kind: Service
metadata:
  name: sftpgo
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 2121
      protocol: TCP
      targetPort: 2121
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: kustomize-jellyfin