apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kustomize-jellyfin-media
  namespace: jellyfin
  labels:
    disk-dashboard: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2500Gi
  storageClassName: openebs-zfspv-affinity
