---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-rtorrent
  namespace: jellyfin
spec:
  encryptedData:
    rclone.conf: AgAmtxxDJQ2rgjFPK1BEliLqw+VsqajK/3bguiOAWARo7MaZk9p4abhKCKBWWAfH9C5VpdHgvXR0b/+2suvC0Xvs8TvHDChf2VN+/2QvD6jbFPC0V0P+bQKNNsLGdj3zSbP+Hu/N0ONTYbW68pznVbBbpcq5MrKZ3mfumi87QgYrsVOn8+NJHxhcptRED+CrREs5kFupw3PDpf9mzg80gnX4kIaKRHHRNgEkvg005j+eIa+hL3FPUHmwWanJ0xAwHJAXuskFFuAVMPuuQrlPRHGJZNk1vtTKr58M0RBRzi2ToucUZnDAaxQ3xaBKvPTSoGKH06bSxbFCKSEY4Rr+vGkqRNC+VJTgOCEkXo+OdNOMTvf36kg9WoPOHzc5fa1nrxEkNF99OwQDea6cFOvy8tOUg4HygWd6QRLdFEvKNBRNJi/RqbrKDxp63FcOm6QxWTKZLfhhYqh9ebs9H9xKeFlhMb2iuem1Z2DmCLNgWfZ2LzziKRd2bAzT2Fx0XhBaXRixA7paQGsRGK/cd26Uxkx2PsFwTpadFMc1HNY1JMJUSt4jCyy3T7VpzIagvC6j7tM8A7IG7JKnz1clK82r08ju1mM/SPeXeUhs/C1afvcfKmcTGjkS/tKEADvfTpYk3ZUu/KNp6qqQ9K7QzhlipYaTqW61f7M3Xz98UUjDUL+tTKdt546FH6YNjFcrCnOHRMyWUwVEznBo6aCarJUlf0+LER9BLR/HBAeJThzl8fMK/FsPYdDIuTXTQkJfJ+83+DiWHIPYdRtdiKA4XiNtmaNynhuxphu9cV+fEsv8M7O/2OYlyBW7xuy957HstlWmjogDddidQuBE1MziKlDsjtYkWMi7gb5IuCOSaxIKUgk10DbuvKY/yXwo8ySj2mEaV+uKw0JyO5nUEmfcxcXWfpPCsOh1o0AjoY5+OOLNJoSkY/W/tjheNsitXALYswkTf0lYKn6tTcODA0aMI6z47Ndlm5ID5Zs0ODnjouCnqxCDngwCDzAnDw8WZxa38tvCZB/Dgdk3nue9eDSKBzIfgnvc5X7gWE6V+HJbnHxuS6sf/1QsOBFCULhelQ0vqPaLugBRAxqx5qPkSbEz/YQE6WtD1bOu
  template:
    metadata:
      creationTimestamp: null
      name: rclone-rtorrent
      namespace: jellyfin
