---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-rtorrent
  namespace: jellyfin
spec:
  encryptedData:
    rclone.conf: AgCXG/WZt9J+opbynbDSxm22vVUZoi5qK17Gy6Ee/p82jOyvOJRirn0ibl4i+dj0QkVBoBvRPrL1R1aAHEEsVxFtBKlYrWQdNQFnUVaGwIyfpj1MaCYU280qGG7EsHWVVjcYYBezlbExICP/IzljnBdf7Gp+JPfSFYz4pW5dhUg4kA8xfkEcSUvcgSGESYUIlAsqTqMzltLaNZBSs2kPVowr0JcuilpmVE1loGk/u+X8VHT/nM+hlfGarH+BJozQObSMD1QYr9KStDRztynsYEiwBBk0QAF0ey6mU7bBHidxDMYFilqCc86vbKTPObp794rcmrudQj+DVQPohO5WQRfFW33Ivcxadi2FouOWMvIvwbkSRdo1Ppc1lm2vo6HzH0AAaUroHyomc2Dv3wyiz9KkG41zgf4GbhwycWHDLG+HLoEQzA0YEz67/JMC5KgpNWsdENzI9aVwxF1SPwTev1+aoaQ4CZuoIKDtXMYYruLhBYIGQchk/7mfLff6W74kvOmSqDgiqt/gm6+RN8C7TOFQ9os3Yn+ofoJHWJcaFmURKbQ2/WGf8BpN1IJNZYfnRj4mNRgFhvPdUs9eh/dAHbybAOGFiOdV8LcHzirmERoHGNfb9KxgUHH/VVMEP5OAK8qZTbnJFtHiRh+NCsU7PGFwHiFKVQztKiUU+YvI1XFbLtJXJOFpY12qQ6WidNZhWLvcWQXZtfK2i195kN+HWudJQ0RIkIXLYRyZv5X3KakGlXwbwutPUrYvL0EoHwvYmSbmBYKRrf/Mlc096BOTZo/5Agwk79C0QNNunEgf2R6+lYM=
  template:
    metadata:
      creationTimestamp: null
      name: rclone-rtorrent
      namespace: jellyfin
