apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-config
  namespace: bookshelf
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-media
  namespace: bookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: openebs-zfspv
