---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dynu-secret
  namespace: cert-manager2
spec:
  encryptedData:
    api-key: AgA4DnNwCzpc2JGjsX1VBT3iXJHo0D2AO8FhPRf5crjZGhib6P8+dVlLmqfqP95o/kFGNsFcUGq4QnjMvwxlGbT6d++VaFL7zuVvWw1lPu/O3Up6iKIgP3+ixtGQ/J5zVE7c40qvtPs44JFxyQEwaTA5KinEXcaMPNKtXyjg1WLS0Dtr8SNBjdFrGIuWyQ6z4u3JMeN6JibPIUeBDeN93uXd92xSI30zqE0ZHbqMJY9lPdxdmNT4ANKQkgdOmSjovpEFaKAUdtfSCmgZ+FXtfIIE2EMlOTLeGsp8xcVRFlSBd2tEWcjZXi04lsY9UM8NUBtuZZW7bk6Ft+99DCyGnUwxbOl6QwF5gdmGyNFP/etf4xQU+y+XCFX5gM+TwLk/fNhhkM0nojuwuuRWl39oOkVjbAMC5tTarRLUUTF1aUCNMnLsh5iPXtShCCB7ADEh3iJQvK8U2EEcDHYS3NrN/EjArXpPfuD02mdzkghGuvRoXQtU6RSwPzk1XQw0AfvPz3ff5snmrVJowdZ4RlZbK16/+Lh7AgSWiaJw2gd0ou4lT6hUm/ICzXSBM5Op9RUUG74SkEyZRoYOrkN476HfJElGZuNk1i+UwozGFpMl3gnX9qngu5iMbw/gpp0hI2oWLUO7Gbks/Xzvd8GRuFXTV6t4tgVldqUchn6+IuZGK39YBPwMPUqJZJtksB6W7ZNLeFklxE4NWaNfMvYc/RqNOUl1zobcQ8JDuZvrIO3xfpXYDQ==
  template:
    metadata:
      name: dynu-secret
      namespace: cert-manager2
    type: Opaque
