---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-alert-topic
  namespace: monitoring
spec:
  encryptedData:
    topic: AgCccAsRCpeZdnVx4/KNX4FQcYjQ7Bc9+6XvbJSVKM9dlLAAlSGzY9RtTZGfNb4XspvevtgcFAUtdakcGH+Fb/QBEQrcxXdVj6vXaR3ejwMk9aOAbyC668zrQKJp/1/9f8+43tGEcbNRTMbIFDX4Ik62zuOdlgck7kze0+zxOwtvYdQ7sQT/mU4gOlIDBjoC1IpCDMbtyyUUnp2vv8ShGXCaRNc91skhyvP4LBEDTEtHZHGHfYyBH35+Xp7Vv7mZ8gDX8QNK8hJGqc11L1b2jBfKOjgVQ98SIdIed4+nuQ3pxDEf4vPShkdORdQJeCzSAoKdmyvq/oYhKCvlRMwHsKOAFZONm4C2rPhBjZ0bPoxiPWIGWZvzG48cYMWM00LCRZpHYv1EHsyl7hwv6ADBkzW0AY7F6YERt/Iu4VOVmBptcgI1dw2iPFuDkh+JXJzE65QddEjtrafOnhLsX+7GF4iXmIyRBgi0Jam2TKJddO0tvHM9npKDXah7smy+2rFW5sbgSELefj/Z2GPsVo+N8zWXcPLZWDTxJ71S19epK6jFQbcSeQ/9tQpXMMwEGXE61cDVG61xpvfc/ejLqLJ8LWbl0wx2sF/W3sqi5L5PyoVH1KWLNqtJmCLp1u40y7zn3Nw5sT4kH8MZCItn0VH3gmZjML6Nb5aT8of4o40JTRMoKUDR9+gQWQLMWnyFf46VuDHTEjDd9DZJZfBtvqNOo5hq
  template:
    metadata:
      name: ntfy-alert-topic
      namespace: monitoring
