apiVersion: v1
kind: Service
metadata:
  name: appflowy-cloud
  namespace: appflowy
spec:
  selector:
    app: appflowy-cloud
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: appflowy-cloud
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-cloud
  namespace: appflowy
spec:
  selector:
    matchLabels:
      app: appflowy-cloud
      namespace: appflowy
  template:
    metadata:
      labels:
        app: appflowy-cloud
        namespace: appflowy
    spec:
      containers:
      - name: appflowy-cloud
        image: appflowyinc/appflowy_cloud:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: POSTGRES_PASSWORD
        - name: APPFLOWY_GOTRUE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_ADMIN_EMAIL
        - name: APPFLOWY_GOTRUE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_ADMIN_PASSWORD
        - name: APPFLOWY_GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_JWT_SECRET
        - name: AI_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: OPENAI_API_KEY
        - name: APPFLOWY_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: APPFLOWY_S3_ACCESS_KEY
        - name: APPFLOWY_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: APPFLOWY_S3_SECRET_KEY
        - name: GOTRUE_JWT_EXP
          value: "7200"
        - name: APPFLOWY_DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/appflowy"
        - name: APPFLOWY_ENVIRONMENT
          value: "production"
        - name: APPFLOWY_REDIS_URI
          value: redis://redis:6379
        - name: APPFLOWY_GOTRUE_BASE_URL
          value: http://gotrue:9999
        - name: APPFLOWY_GOTRUE_EXT_URL
          value: https://appflowy.ugard.mywire.org/gotrue
        - name: AI_SERVER_HOST
          value: ai
        - name:  AI_SERVER_PORT
          value: "5001"
          #       - APPFLOWY_S3_CREATE_BUCKET=${APPFLOWY_S3_CREATE_BUCKET}
#       - APPFLOWY_S3_USE_MINIO=${APPFLOWY_S3_USE_MINIO}
        - name: APPFLOWY_S3_MINIO_URL
          value: http://minio.minio:9000
#       - APPFLOWY_S3_ACCESS_KEY=${APPFLOWY_S3_ACCESS_KEY}
#       - APPFLOWY_S3_SECRET_KEY=${APPFLOWY_S3_SECRET_KEY}
        - name:  APPFLOWY_S3_BUCKET
          value: appflowy
        - name:  APPFLOWY_WEB_URL
          value: https://appflowy.ugard.mywire.org/
#       - APPFLOWY_S3_REGION=${APPFLOWY_S3_REGION}
---


# appflowy_cloud:
#     restart: on-failure
#     environment:
#       - RUST_LOG=${RUST_LOG:-info}
#       - APPFLOWY_ENVIRONMENT=production
#       - APPFLOWY_DATABASE_URL=${APPFLOWY_DATABASE_URL}
#       - APPFLOWY_REDIS_URI=${APPFLOWY_REDIS_URI}
#       - APPFLOWY_GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
#       - APPFLOWY_GOTRUE_JWT_EXP=${GOTRUE_JWT_EXP}
#       - APPFLOWY_GOTRUE_BASE_URL=${APPFLOWY_GOTRUE_BASE_URL}
#       - APPFLOWY_GOTRUE_EXT_URL=${API_EXTERNAL_URL}
#       - APPFLOWY_GOTRUE_ADMIN_EMAIL=${GOTRUE_ADMIN_EMAIL}
#       - APPFLOWY_GOTRUE_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD}
#       - APPFLOWY_S3_CREATE_BUCKET=${APPFLOWY_S3_CREATE_BUCKET}
#       - APPFLOWY_S3_USE_MINIO=${APPFLOWY_S3_USE_MINIO}
#       - APPFLOWY_S3_MINIO_URL=${APPFLOWY_S3_MINIO_URL}
#       - APPFLOWY_S3_ACCESS_KEY=${APPFLOWY_S3_ACCESS_KEY}
#       - APPFLOWY_S3_SECRET_KEY=${APPFLOWY_S3_SECRET_KEY}
#       - APPFLOWY_S3_BUCKET=${APPFLOWY_S3_BUCKET}
#       - APPFLOWY_S3_REGION=${APPFLOWY_S3_REGION}
#       - APPFLOWY_S3_PRESIGNED_URL_ENDPOINT=${APPFLOWY_S3_PRESIGNED_URL_ENDPOINT}
#       - APPFLOWY_MAILER_SMTP_HOST=${APPFLOWY_MAILER_SMTP_HOST}
#       - APPFLOWY_MAILER_SMTP_PORT=${APPFLOWY_MAILER_SMTP_PORT}
#       - APPFLOWY_MAILER_SMTP_USERNAME=${APPFLOWY_MAILER_SMTP_USERNAME}
#       - APPFLOWY_MAILER_SMTP_EMAIL=${APPFLOWY_MAILER_SMTP_EMAIL}
#       - APPFLOWY_MAILER_SMTP_PASSWORD=${APPFLOWY_MAILER_SMTP_PASSWORD}
#       - APPFLOWY_MAILER_SMTP_TLS_KIND=${APPFLOWY_MAILER_SMTP_TLS_KIND}
#       - APPFLOWY_ACCESS_CONTROL=${APPFLOWY_ACCESS_CONTROL}
#       - APPFLOWY_DATABASE_MAX_CONNECTIONS=${APPFLOWY_DATABASE_MAX_CONNECTIONS}
#       - AI_SERVER_HOST=${AI_SERVER_HOST}
#       - AI_SERVER_PORT=${AI_SERVER_PORT}
#       - AI_OPENAI_API_KEY=${AI_OPENAI_API_KEY}
#       - APPFLOWY_ADMIN_FRONTEND_PATH_PREFIX=${ADMIN_FRONTEND_PATH_PREFIX}
#       - APPFLOWY_WEB_URL=${APPFLOWY_WEB_URL}
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         FEATURES: ""
#     image: 
#     depends_on:
#       gotrue:
#         condition: service_healthy