apiVersion: v1
kind: Service
metadata:
  name: gotrue
  namespace: appflowy
spec:
  selector:
    app: gotrue
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      name: gotrue
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotrue
  namespace: appflowy
spec:
  selector:
    matchLabels:
      app: gotrue
      namespace: appflowy
  template:
    metadata:
      labels:
        app: gotrue
        namespace: appflowy
    spec:
      containers:
      - name: gotrue
        image: appflowyinc/gotrue:latest
        ports:
        - containerPort: 9999
        env:
        - name: SUPABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: SUPABASE_PASSWORD
        - name: GOTRUE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_ADMIN_EMAIL
        - name: GOTRUE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_ADMIN_PASSWORD
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: appflowy
              key: GOTRUE_JWT_SECRET
        - name: GOTRUE_JWT_EXP
          value: "7200"
        - name: DATABASE_URL
          value: "postgres://supabase_auth_admin:$(SUPABASE_PASSWORD)@postgres:5432/appflowy"
        - name: GOTRUE_JWT_ADMIN_GROUP_NAME
          value: "supabase_admin"
        - name: PORT
          value: "9999"
        - name: API_EXTERNAL_URL
          value: https://appflowy.ugard.mywire.org/gotrue
        - name: GOTRUE_DB_DRIVER
          value: postgres
        - name:  GOTRUE_SITE_URL
          value: appflowy-flutter://
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotrue
  namespace: appflowy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: appflowy-gotrue-stripprefix@kubernetescrd
spec:
  rules:
  - host: appflowy.ugard.mywire.org
    http:
      paths:
        - path: "/gotrue"
          pathType: Prefix
          backend:
            service:
              name: gotrue
              port:
                number: 9999
  tls:
  - hosts:
    - appflowy.ugard.mywire.org
    secretName: tls-gotrue-appflowy-ingress-http
---
apiVersion: traefik.io/v1
kind: Middleware
metadata:
  name: gotrue-stripprefix
  namespace: appflowy
spec:
  stripPrefix:
    prefixes:
      - /gotrue