apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: appflowy
spec:
  selector:
    app: admin-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: admin-frontend
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: appflowy
spec:
  selector:
    matchLabels:
      app: admin-frontend
      namespace: appflowy
  template:
    metadata:
      labels:
        app: admin-frontend
        namespace: appflowy
    spec:
      containers:
      - name: admin-frontend
        image: appflowyinc/admin_frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ADMIN_FRONTEND_REDIS_URL
          value: redis://redis:6379
        - name: ADMIN_FRONTEND_GOTRUE_URL
          value: http://gotrue:9999
        - name: ADMIN_FRONTEND_APPFLOWY_CLOUD_URL
          value: http://appflowy-cloud:8000
        - name: ADMIN_FRONTEND_PATH_PREFIX
          value: ""
        - name: ADMIN_FRONTEND_HOST
          value: "0.0.0.0"
        - name: ADMIN_FRONTEND_PORT
          value: "80"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-frontend
  namespace: appflowy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.middlewares: appflowy-webcors@kubernetescrd
  spec:
  rules:
  - host: admin.appflowy.ugard.win
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: admin-frontend
              port:
                number: 80
  tls:
  - hosts:
    - admin.appflowy.ugard.win
    secretName: tls-admin-appflowy-ingress-http
---
apiVersion: v1
kind: Service
metadata:
  name: appflowy-web
  namespace: appflowy
spec:
  selector:
    app: appflowy-web
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: appflowy-web
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-web
  namespace: appflowy
spec:
  selector:
    matchLabels:
      app: appflowy-web
      namespace: appflowy
  template:
    metadata:
      labels:
        app: appflowy-web
        namespace: appflowy
    spec:
      containers:
      - name: appflowy-web
        image: appflowyinc/appflowy_web:latest
        ports:
        - containerPort: 80
        env:
        - name: AF_BASE_URL
          value: https://appflowy.ugard.win/
        - name: AF_GOTRUE_URL
          value: https://appflowy.ugard.win/gotrue
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appflowy-web
  namespace: appflowy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.middlewares: appflowy-webcors@kubernetescrd
  spec:
  rules:
  - host: web.appflowy.ugard.win
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: appflowy-web
              port:
                number: 80
  tls:
  - hosts:
    - web.appflowy.ugard.win
    secretName: tls-web-appflowy-ingress-http
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: webcors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "https://appflowy.ugard.win"
      - "https://web.appflowy.ugard.win"
    accessControlMaxAge: 100
    addVaryHeader: true