apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone
  namespace: rtorrent
spec:
  selector:
    matchLabels:
      app: rclone
      namespace: rtorrent
  template:
    metadata:
      labels:
        app: rclone
        namespace: rtorrent
    spec:
      containers:
      - name: rclone
        image: docker.io/rclone/rclone:latest
        command: [ "rclone" ]
        args:
        - serve
        - webdav
        - --addr
        - :8888
        - /media
