apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone
  namespace: rtorrent
spec:
  selector:
    matchLabels:
      app: rclone
      namespace: rtorrent
  template:
    metadata:
      labels:
        app: rclone
        namespace: rtorrent
    spec:
      containers:
      - name: rclone
        image: docker.io/rclone/rclone:latest
        command: [ "rclone" ]
        args:
        - serve
        - webdav
        - --addr
        - :8888
        - /home
        volumeMounts:
        - mountPath: /host
          name: host-root
        nodeSelector:
          kubernetes.io/hostname: "talos-95t-m8m"
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: /
          type: ""
        name: host-root
---
apiVersion: v1
kind: Service
metadata:
  name: rclone
  namespace: rtorrent
spec:
  selector:
    app: rclone
  ports:
  - port: 8888
    targetPort: 8888
    name: webdav
    protocol: TCP