apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: rtorrent
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Warsaw"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
          mountPropagation: HostToContainer
        - name: media
          mountPath: /media
          mountPropagation: HostToContainer
      - name: rclone-bridge-downloads
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        command: ["/usr/local/bin/rclone"]
        args:
        - mount
        - ":webdav:"
        - /downloads
        - "--webdav-url"
        - "http://rtorrent.rtorrent.svc.cluster.local:8888"
        - "--vfs-cache-mode"
        - "full"
        - "--allow-other"
        volumeMounts:
        - name: downloads
          mountPath: /downloads
          mountPropagation: Bidirectional
        - name: fuse-device
          mountPath: /dev/fuse
      - name: rclone-bridge-media
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        command: ["/usr/local/bin/rclone"]
        args:
        - mount
        - ":webdav:"
        - /media
        - "--webdav-url"
        - "http://jellyfin-bridge.jellyfin.svc.cluster.local:8080"
        - "--vfs-cache-mode"
        - "full"
        - "--allow-other"
        - "--dir-cache-time"
        - "10s"
        volumeMounts:
        - name: media
          mountPath: /media
          mountPropagation: Bidirectional
        - name: fuse-device
          mountPath: /dev/fuse
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: downloads
        emptyDir: {}
      - name: media
        emptyDir: {}
      - name: fuse-device
        hostPath:
          path: /dev/fuse
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: rtorrent
spec:
  selector:
    app: radarr
  ports:
  - port: 7878
    targetPort: 7878
    name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: rtorrent
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  rules:
  - host: radarr.ugard.win
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: radarr
              port:
                number: 7878
  tls:
  - hosts:
    - radarr.ugard.win
    secretName: tls-radarr-ingress-http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: rtorrent
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
