apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-data
  namespace: rtorrent
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block