apiVersion: v1
kind: Namespace
metadata:
  name: drone-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: drone-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-runner
  namespace: drone-runner
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-runner
  namespace: drone-runner
subjects:
- kind: ServiceAccount
  name: drone-runner
  namespace: drone-runner
roleRef:
  kind: Role
  name: drone-runner
  apiGroup: rbac.authorization.k8s.io
