apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-dr
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-a11de6d5-23a4-4d0c-affb-f9686a2383a5-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-a11de6d5-23a4-4d0c-affb-f9686a2383a5-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: paperless-data-dr
    namespace: paperless
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-1d5a3e9c-4cab-4bce-a6d7-ca9e3f210c81
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-1d5a3e9c-4cab-4bce-a6d7-ca9e3f210c81
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-dr
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-1a17cbe8-5a59-4880-afed-152958f72458-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-1a17cbe8-5a59-4880-afed-152958f72458-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: paperless-media-dr
    namespace: paperless
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-ccaff179-021f-4ad0-9c22-c5ec5c8a7196
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-ccaff179-021f-4ad0-9c22-c5ec5c8a7196
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: migrate
  name: migrate
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrate
  serviceName: migrate
  template:
    metadata:
      labels:
        app: migrate
    spec:
      containers:
      - image: docker.io/alpine:latest
        name: shell
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: source-immich
            mountPath: /source
          - name: source-pg
            mountPath: /source_pg
          - name: source-redis
            mountPath: /source_redis
          - name: dest-immich
            mountPath: /dest
          - name: dest-pg
            mountPath: /dest_pg
          - name: dest-redis
            mountPath: /dest_redis
      volumes:
        - name: source-immich
          persistentVolumeClaim:
            claimName: immich-data-dr
        - name: dest-immich
          persistentVolumeClaim:
            claimName: immich-data-pvc
        - name: source-redis
          persistentVolumeClaim:
            claimName: immich-redis-dr
        - name: dest-redis
          persistentVolumeClaim:
            claimName: immich-redis-pvc
        - name: source-pg
          persistentVolumeClaim:
            claimName: immich-postgres-dr
        - name: dest-pg
          persistentVolumeClaim:
            claimName: immich-postgres-pvc
      