apiVersion: batch/v1
kind: Job
metadata:
  name: openarchiver-migrate
  namespace: openarchiver
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: postgres-access
      containers:
      - name: migrate
        image: bitnami/kubectl:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_PASSWORD
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          echo "Waiting for PostgreSQL pod to be ready..."
          until kubectl get pod -n postgres -l app=postgres -o jsonpath='{.items[0].status.phase}' | grep -q Running; do
            echo "PostgreSQL pod is not ready - sleeping"
            sleep 2
          done
          
          POSTGRES_POD=$(kubectl get pod -n postgres -l app=postgres -o jsonpath='{.items[0].metadata.name}')
          echo "Found PostgreSQL pod: ${POSTGRES_POD}"
          
          echo "Waiting for PostgreSQL service to accept connections..."
          until kubectl exec -n postgres "${POSTGRES_POD}" -- pg_isready -U postgres; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          
          echo "PostgreSQL is up - executing migration"
          
          echo "Creating database if not exists..."
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
            kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -c "CREATE DATABASE $POSTGRES_DB"
          
          echo "Creating user if not exists..."
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" || echo "User already exists"
          
          echo "Granting database privileges..."
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER"
          
          echo "Granting schema privileges..."
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -d "$POSTGRES_DB" -c "GRANT ALL ON SCHEMA public TO $POSTGRES_USER"
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -d "$POSTGRES_DB" -c "GRANT ALL ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER"
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -d "$POSTGRES_DB" -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER"
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -d "$POSTGRES_DB" -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $POSTGRES_USER"
          kubectl exec -n postgres "${POSTGRES_POD}" -- psql -U postgres -d "$POSTGRES_DB" -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $POSTGRES_USER"
          
          echo "Migration completed successfully"
