apiVersion: batch/v1
kind: Job
metadata:
  name: openarchiver-migrate
  namespace: openarchiver
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: postgres:17-alpine
        env:
        - name: PGHOST
          value: postgres.postgres
        - name: PGPORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: openarchiver
              key: POSTGRES_PASSWORD
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "Waiting for PostgreSQL to be ready..."
          until psql -h postgres.postgres -U "$POSTGRES_USER" -d postgres -c '\q'; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          
          echo "PostgreSQL is up - executing migration"
          
          echo "Creating database if not exists..."
          psql -h postgres.postgres -U "$POSTGRES_USER" -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
            psql -h postgres.postgres -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE $POSTGRES_DB"
          
          echo "Granting privileges..."
          psql -h postgres.postgres -U "$POSTGRES_USER" -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER"
          
          echo "Migration completed successfully"
