apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openarchiver-data
  namespace: openarchiver
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
