apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-access
  namespace: openarchiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-exec
  namespace: openarchiver
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-exec-binding
  namespace: openarchiver
subjects:
- kind: ServiceAccount
  name: postgres-access
  namespace: openarchiver
roleRef:
  kind: Role
  name: postgres-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-exec-external
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
  resourceNames: ["postgres-0"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-exec-external-binding
subjects:
- kind: ServiceAccount
  name: postgres-access
  namespace: openarchiver
roleRef:
  kind: ClusterRole
  name: postgres-exec-external
  apiGroup: rbac.authorization.k8s.io
