apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openarchiver-valkey-data
  namespace: openarchiver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
