apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: gitea-actions-runner
  namespace: gitea
spec:
  jobTargetRef:
    selector:
      matchLabels:
        app: gitea-actions-runner
    template:
      metadata:
        labels:
          app: gitea-actions-runner
      spec:
        serviceAccountName: gitea-actions-runner
        containers:
        - name: runner
          image: gitea/act_runner:latest
          args:
            - daemon
            - --config
            - /config.yaml
          env:
          - name: GITEA_INSTANCE_URL
            value: "http://gitea-web.gitea:80"
          - name: GITEA_RUNNER_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-actions-runner
                key: GITEA_RUNNER_REGISTRATION_TOKEN
          - name: DOCKER_BUILDKIT
            value: "0"
          volumeMounts:
          - name: config
            mountPath: /config.yaml
            subPath: config.yaml
          - name: kaniko-cache
            mountPath: /kaniko/.docker
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        volumes:
        - name: config
          configMap:
            name: gitea-actions-runner
        - name: kaniko-cache
          emptyDir: {}
        restartPolicy: Never
  pollingInterval: 30
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  maxReplicaCount: 1
  scalingStrategy:
    strategy: custom
    customScalingQueueLengthDeduction: 1
  triggers:
  - type: http
    metadata:
      url: "http://gitea-web.gitea/api/v1/user/actions/runs?status=pending"
      method: "GET"
    authenticationRef:
      name: keda-http-cred
  - type: http
    metadata:
      url: "http://gitea-web.gitea/api/v1/user/actions/runs?status=queued"
      method: "GET"
    authenticationRef:
      name: keda-http-cred
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-http-cred
  namespace: gitea
spec:
  secretTargetRef:
  - parameter: headers.Authorization
    name: gitea-actions-runner
    key: GITEA_API_TOKEN
