---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: obsidian-gitea-credentials
  namespace: obsidian
spec:
  encryptedData:
    GITEA_TOKEN: AgBVyoXk1sqfvuaOkwXEBGGYAmr6BrxniEYLc3C+hdO0EpOo8viB2PcQc41FSwxYnH6ztTomIBfLrTJNoi8U6YhNYRICqYImF7huwylfpm9UpU4gd8gXWl06KSI/hCfLbczUvACWNMutmz6MSzzqFcdD9Bm2Qwa4DF3+1WT8N2wpur9+pJMpLpVdSeXeCC+DSEdOhuT/jCvYw9VYy/kxj8Wjgzh3qo/w9XF9LtK/rMOr+xbX/gM/SxggAgxz+qYjadUonn91/9BPloKc8tr0/M/h415XmeqKMbZEwSrC59KQcfF7WY/r5QUbeg1tpgA4gZRYOrsejMHAmQKer7A3ECMfdTEM5BY/So+pS2N+fA2V+t5l/7U31LIq/wJ1K+GRLkEmStA2KWOilk9X11BPrYkGBi7aXG+M0UvOZF4eJETKF0RJEKE5Wqe4nYc97mEznpyhY1XEAVhWKUgvvp3Py1VV6K2HAOSnIT6TZ70oOIc+M3UYxlPPFS/4UoTyfZesmTthkPSQiIYAUBlpkwjJ+7O+JkpnRImSv5b4h7AJYFBtkPaHxnImO+kMUy1szVEBt0it2B8ll7NByp0ueMyTwrY7JIEeqVPGdg/KDK3jIWicsQl4JRdcFmeBm9TMh+pj6lqVXbQ9bpJBYWNqBxN3YY507lmy35dAqJdWSEWGJSuK13HBCv6ti+3+Ga+oXJtrO4WcE9hcnQzd4YjyZ/B3z89bLAXjIKyWS/F2L9QzmvbO5C1dND9uM+Q9
  template:
    metadata:
      name: obsidian-gitea-credentials
      namespace: obsidian
