apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-data-ceph
  namespace: obsidian
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block