apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: garage-meta-ceph
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
      - garage
    includedResources:
      - persistentvolumeclaims
    labelSelector:
      matchLabels:
        backup-this-pvc: "true"
    snapshotMoveData: true
    storageLocation: scaleway
    ttl: 720h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: garage-data-zfs
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
      - garage
    includedResources:
      - persistentvolumeclaims
    labelSelector:
      matchLabels:
        backup-strategy: zfs-local
    snapshotMoveData: false
    storageLocation: scaleway
    ttl: 720h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: postgres-backup
  namespace: velero
spec:
  schedule: "0 4 * * *"
  template:
    includedNamespaces:
      - postgres
    excludedResources:
      - persistentvolumes
    hooks:
      resources:
        - name: postgres-dump
          includedNamespaces:
          - postgres
          includedResources:
          - pods
          labelSelector:
            matchLabels:
              app: postgres
          pre:
            - exec:
                container: postgres
                command:
                - /bin/bash
                - -c
                - "PGPASSWORD=$POSTGRES_PASSWORD pg_dumpall -U $POSTGRES_USER > /backups/dump.sql"
                onError: Fail
                timeout: 10m
          post:
            - exec:
                container: postgres
                command:
                - /bin/bash
                - -c
                - "rm /backups/dump.sql"
                onError: Continue
                timeout: 1m
    snapshotMoveData: false
    snapshotVolumes: false
    storageLocation: garage
    ttl: 720h0m0s
