apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-dr
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 47Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-0f0978a4-ad40-45a5-86cc-5f866919715d-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-0f0978a4-ad40-45a5-86cc-5f866919715d-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 47Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: immich-data-dr
    namespace: immich
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-ef1f2089-26d6-4260-87f4-424814fe68a5
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-ef1f2089-26d6-4260-87f4-424814fe68a5
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-dr
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-026bd3f9-ca64-481f-bef4-59c2b84a3180-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-026bd3f9-ca64-481f-bef4-59c2b84a3180-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: immich-postgres-dr
    namespace: immich
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-c5082b9a-458d-45cb-9aee-d5b77f3e46d3
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-c5082b9a-458d-45cb-9aee-d5b77f3e46d3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-dr
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-6dd5e67a-86ac-4fe9-af55-7e68b7e2494f-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-6dd5e67a-86ac-4fe9-af55-7e68b7e2494f-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: immich-redis-dr
    namespace: immich
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-66a9c9fb-1e85-413e-8f5a-1b61ca0bfcb9
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-66a9c9fb-1e85-413e-8f5a-1b61ca0bfcb9
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: migrate
  name: migrate
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrate
  serviceName: migrate
  template:
    metadata:
      labels:
        app: migrate
    spec:
      containers:
      - image: docker.io/alpine:latest
        name: shell
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: source-immich
            mountPath: /source
          - name: source-pg
            mountPath: /source_pg
          - name: source-redis
            mountPath: /source_redis
          - name: dest-immich
            mountPath: /dest
          - name: dest-pg
            mountPath: /dest_pg
          - name: dest-redis
            mountPath: /dest_redis
      volumes:
        - name: source-immich
          persistentVolumeClaim:
            claimName: immich-data-dr
        - name: dest-immich
          persistentVolumeClaim:
            claimName: immich-data-pvc
        - name: source-redis
          persistentVolumeClaim:
            claimName: immich-redis-dr
        - name: dest-redis
          persistentVolumeClaim:
            claimName: immich-redis-pvc
        - name: source-pg
          persistentVolumeClaim:
            claimName: immich-postgres-dr
        - name: dest-pg
          persistentVolumeClaim:
            claimName: immich-postgres-pvc
      