apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyfold
  namespace: manyfold
spec:
  selector:
    matchLabels:
      app: manyfold
      namespace: manyfold
  template:
    metadata:
      labels:
        app: manyfold
        namespace: manyfold
    spec:
      initContainers:
      - command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /usr/src/app/tmp /usr/src/app/log /models || true
            chmod -R g+rwxs /usr/src/app/tmp /usr/src/app/log /models || true
        image: alpine:3.20
        imagePullPolicy: IfNotPresent
        name: fix-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /models
            name: model-data
          - mountPath: /usr/src/app/tmp
            name: tmp-dir
          - mountPath: /usr/src/app/log
            name: log-dir
      containers:
      - name: manyfold
        image: ghcr.io/manyfold3d/manyfold:0.127.0
        args:
          - foreman start
        command:
          - /bin/ash
          - '-c'
        envFrom:
         - secretRef:
            name: manyfold
            optional: false
        volumeMounts:
          - name: model-data
            mountPath: /models
          - mountPath: /usr/src/app/tmp
            name: tmp-dir
          - mountPath: /usr/src/app/log
            name: log-dir
        env:
        - name: TZ
          value: "Europe/Warsaw"
        - name: DATABASE_ADAPTER
          value: "postgresql"
        - name: DATABASE_HOST
          value: postgres.postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: "REDIS_URL"
          value: "redis://redis:6379/1"
        - name: MANYFOLD_LOG_LEVEL
          value: debug
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: HOME
          value: /usr/src/app/tmp
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: manyfold-data-pvc
        - emptyDir: {}
          name: tmp-dir
        - emptyDir: {}
          name: log-dir
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: manyfold
spec:
  selector:
    matchLabels:
      app: redis
      namespace: manyfold
  template:
    metadata:
      labels:
        app: redis
        namespace: manyfold
    spec:
      containers:
      - name: redis
        image: docker.io/library/redis:7
        resources:
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: manyfold
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: manyfold
  namespace: manyfold
spec:
  selector:
    app: manyfold
  ports:
  - port: 3214
    targetPort: 3214
    name: web
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manyfold
  namespace: manyfold
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  rules:
  - host: manyfold.ugard.win
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: manyfold
              port:
                number: 3214
  tls:
  - hosts:
    - manyfold.ugard.win
    secretName: tls-manyfold-http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-data-pvc
  namespace: manyfold
  labels:
    "backup-this-pvc": "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: rook-ceph-block
---
