apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mqtt-internal
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: mqtt-internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
