---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-credentials
  namespace: mqtt-internal
spec:
  encryptedData:
    ALERT_WEBHOOK_PASSWORD: AgC3whsEWku4fnXS5N/Bw63cedVxzDVpuqTuDZlReKjciMET3vtVAbfOwk0BFSlRPUV/EwbXIdQkvFwK+Gf7r1O9MKuYXrWs6HcBihPznLEX4uVcuM1AWPHuN0EzwSAJT4YVNjAwtSZ6qEaYV+V0dbcpon/2e1jXJhn89koigqUEUVlR02C2Yr3okQQn657AZVafz8tRWrKIoGXqafCngsnDv1AAN1VymWT/CJFNi2sGqegU94pPyQa6K3ezOPypNHPhcS7hNPDYSyOsXg6M2x02wq/3zCeVrm0Hdamkz0K+Z5co34Vi9MyWhCYfLnVPFJvE7m8eMyll/u6VvFNero2twf6jAuak6UOE3jI/3V2+v5NgJfSqGLaAVQ2huNbXm6jB/eyO9+N9z7zTcY6ZxaqQ/cuCcXtYN0SsESM82xyEm4xjlAo/dty3gG0gYOWmEjpD9mc8BtPHoAOb/h/3jX4qWSGyCjowROjIYZDqfgLQrnBVz5Da8UzQKdnuAVKImqDS9auoG4TbKwZOHMoRnbDImcVemn35E/qh4dqtDfeEByzvZs0cUvJta2qsW2osjGlEzqPKQFCscNAeQBRZ/Gl7lKDv/vKJmfOwsdSyOqyLBswqeiOMd13Trf5f6D1qo+bkA15BaJ7fM15ajeKOewLdiY7VH7A02y7/qnnqcGRUcMW3O3HcwjBkoASpD1oybLkdT+Pbi7DknLi8R3VORLDUB6MlKzx3xmU=
    XMPP_BRIDGE_PASSWORD: AgAnv9DfV/x/pjOVZfQ1k1eBZ8bQHjDx+qh3mSAfiENg2XTneMy7A3TJRiNf5Uhpn8zuL3VYHZUEacjts/BUt8Fl3u61sp2UtacK2c4FDhDhLy3mECfGHfw04dYANu4GR9JAXEhmoGxnOH8KZXXsl5ENfW60IVJNsmhlWI7srAnu3DDlAPY5PJnQGbFq3xeiwgTFfHg4NVCZV4iamBW+ybl44xPm/61jzoLBP/97zaPf/l3RnZ/LcpYVjRy6j6WV4n6JDYvwEFw+timdWkDpRn+XrK0E9hWhv27B/jIpPJoXOSpWjTS9mSIihtSOIoysaycw62sDSCzR82s+0XzeULeouzhWFXH+cGlBHvmClA/WLeLJayc0cJYkgc++WES02uhE4hTmJkZ97bLwIfVQLCIxaBulc5WG73UxOGZUN9feADiS2/bTLi/KZqZQi0rB3Pgyhr2+u6r1EP7+sI7SpP6lkCzWuJuT8pmetCjeEiGMgR5FS6NQuNj7a9JkNQUIPrM8oTaa2rgxPdGjgVL4bLKfW8IzDrFeBgeYvsDSIQZGMRowv53ZKa6j9nkQRsM37evzPfth6BfUaZJctms+XwxvrdnRodWffdgC39BomK+m0cXXZ/me7ROkqYJ6RZWTODfuxjcVvIfyf1JzFqN95VXwDu011Pid8U/5C6DxvREC3PfDCq8uuCfhYf+0o/9YnZcvAIWjifQxn3KKONAolpzX6brQU7Ewwus=
  template:
    metadata:
      name: mosquitto-credentials
      namespace: mqtt-internal
    type: Opaque
