apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: hass
spec:
  ports:
  - name: web
    port: 8123
  selector:
    app: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: hass
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
      namespace: hass
  template:
    metadata:
      labels:
        app: home-assistant
        namespace: hass
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2026.2.1
        resources:
          limits:
            memory: "2Gi"
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: Europe/Warsaw
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name: configmap-file
        - mountPath: /config/automations.yaml
          subPath: automations.yaml
          name: configmap-file
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: hass-ceph-pvc
      - name: configmap-file
        configMap:
          name: home-assistant-configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
  namespace: hass
data:
  known_devices.yaml: |
  automations.yaml: |
    - alias: "Initialize all TRV calibration on startup"
      trigger:
        - platform: homeassistant
          event: start
      action:
        - delay:
            seconds: 15
        - repeat:
            for_each: >
              {{ states.number 
                 | selectattr('entity_id', 'search', '_local_temperature_calibration$')
                 | map(attribute='entity_id') 
                 | list }}
            sequence:
              - service: number.set_value
                target:
                  entity_id: "{{ repeat.item }}"
                data:
                  value: 0
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
    
    mqtt:
     sensor:
     - name: "Thermostat room temperature"
       state_topic: "events/central_heating/otmonitor/roomtemperature"
       unit_of_measurement: "°C"
       device_class: "temperature"
       value_template: "{{ value_json.value }}"
     - name: "Outside temperature"
       state_topic: "events/central_heating/otmonitor/outsidetemperature"
       unit_of_measurement: "°C"
       device_class: "temperature"
       value_template: "{{ value_json.value }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-ceph-pvc
  namespace: hass
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi 
  storageClassName: rook-ceph-block