apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-conf
  namespace: lychee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: openebs-zfspv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-sym
  namespace: lychee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: openebs-zfspv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-uploads
  namespace: lychee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30G
  storageClassName: openebs-zfspv
