apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        env:
        - name: AGH_CONFIG
          valueFrom:
            configMapKeyRef:
              name: adguard-config
              key: AdGuardHome.yaml
        ports:
        - containerPort: 53 #dns
          name: dns
          protocol: UDP
        - containerPort: 3000 #initial setup
          name: http-initial
        - containerPort: 80 #web gui
          name: http
          protocol: TCP
        volumeMounts:
        - name: adguard-data
          mountPath: /opt/adguardhome/work
      volumes:
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-4a8b58c0-fc92-44a7-a7ce-e47decf0d9fb-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph2.rbd.csi.ceph.com
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph2
  creationTimestamp: "2024-09-15T19:52:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-4a8b58c0-fc92-44a7-a7ce-e47decf0d9fb-2
  resourceVersion: "122715812"
  uid: 57c3c859-1d5a-40c7-afa0-d1d62f069282
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: adguard-pvc
    namespace: adguard
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph2
    driver: rook-ceph2.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph2
    volumeAttributes:
      clusterID: rook-ceph2
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-ffe0ea92-ef21-4146-9e90-05de5f74aded
      journalPool: ceph-blockpool
      pool: ceph-blockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1726425819863-8158-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-000a-rook-ceph2-0000000000000001-ffe0ea92-ef21-4146-9e90-05de5f74aded
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.10.254
spec:
  selector:
    app: adguard
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http-initial
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    auth_name: "admin"
    auth_pass: "your-password"
    language: "en"
    rlimit_nofile: 0
    rlimit_nproc: 0
    log_file: ""
    log_syslog: false
    log_syslog_srv: ""
    pid_file: ""
    verbose: false