apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAYJIpXIxwgDfdreD9Mj5s/IJFsLxcydzACdoAcRXLH1/mTVe0lDwatPTfx1QCoWwQhGwjxXuxEE2bbmLH/wfWPSFmgRysESQII5GkTo1KYXs/Pla4uoKYU528vVxFuyjKzGgcIshGHuTnMqla7wyZaZYqFxz+hcF30nVsgG4d3HZp4T6/yqIjRVdCUGLYyvx1hJiFB2AexYiiuiwhWFcBXUMpyHBBohQ+pH1yicruggJt6eQApkxiExX3OaCmjqjt/1cCIimrNMZuBIcuVUA2gZiYzsZmweZNVOausNpTEOpbi7I29Kp+/92X38Cb+OFB2q3xOE55v+vNwq0Y7CWUyVPeBabweGiQxNvh7wClqQnm1TDEh+sRLr/+PjlG8Y1tAfO94b03hHon+7f44/OSfMOcdr7fN8u40SRFc5r/REtuFPjsm5jJunN9ol2n18pAqIZXV7c3JOn3yUKduaonunvWwzq/VcwuRa0mZDzDaEib+SKZi05LwhzZ2AXYzgDYpvliZrN/SWch4mrTXgOOstFn/PKR2SQNIKsZC/eJaaEzneiVJMnIjd9piHsMJAdWVGqrkfyLrLZumZuLWzgHjj7DNrRJMD80EziF/huXSDg5mYpF3sW6swpr9AobcA7QpkRoKPldNYk9EWueXLNKeqiZMrLLL4ltktQLTA7Taa2X584/uPw9lcBJsxrI3JlwcLLXoedF0dyxgfiKlhrNgvSyshqCXuxYiDuWuRIxpzg==
    POSTGRES_USER: AgANSmTNuQnI0rfamQmaHNN2Lp/wSINJ+xRtpGQ32vH/NyX8n6k7OzZIRUihPUwXfYFg+6hyELulH7FdUQvjCwVuxSHqdAoSir4WHbDor19TE8seipqhY77PgR5BS6czNeKItgwzXDTKueUf5j8TpYorgbb4fbzU8XjnaZWMdGCJTjpkm6ttp6iTXPzQAvqWomy7Pa7pqTH9EzKyVXNSQYItMNO8Y2vV174Leg0vlh5LDg5jyAl03zr8emEuBHt9eBiHQK3J7mQx5YkqcOrhSM1YSh3IlF9L3YpC4af5HwKUQ3e6Af3L/otTJRgjlbKMPE1pgOFLFbyGV16p9ua3MgQUEY45a5LJawK1BsdVKIZQtkUNCzxgiqa83sh6pacwCDsOyiwTqZ1A7P0t+NmhzLw+rrCOH5ZvbxHn7PMsU3cL5qe9ZP5ZI4gKQJyCMxW6uY84pixvqeqwbbcI34PpSpUatXwqkw/yB4CAZu/7vqtMneHOor3H7VHA05yI8QbM5v9JQ19FjhRRBkKLoxdsaoZQiySS7z8ErMKmhFu3/8ZlSwO3cZWyfttjLQLQHuMje7KWTjXZ+228reoyRcGU4kgb6lBApX6JksuSh6mHRbz9U0JpBtoMQUFlOPubxi3+CcUMwlXVNzkf1Z8U6UIFgT0dqdS8OK0zie5PzLdQTmt8wg4ceMDFDNNT7p1PAvaZ1E39XYa9fUTkxg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: postgres

