---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-config
  namespace: garage
spec:
  encryptedData:
    garage.toml: AgCwM55Y2vzv/PpHjwhannCtSCqmIcSFPNduBJzpJe2SAfy+Ba9XVUH6+IUOb0b3hynD9oU5QxrZKP7BCNzehuHkh+u+9JFFLmHGjTSf+BO+oZdcpol4P+hIywlj9KEy7zby4arq+xSnq3xNHkrTQ0pwk1/LWMEFhptXrc9PrVzB0PA9QdTdE/b2Ax6262mndfASN9PlpGxk+6qW3Rbjm6EYmKaS/VUbbK50EIZks9Zxf2OyDdPXU6wMJ1b7oBFuVCObjcVquisq97Lovh3AsYEGtWtYuT+/NdtpLaaUMlkfSEcSxXVvzyqNlANnwbzFLXpDL25jPSRJ7b868mVtK2UpsLXcFvor11FkWY0Q6oRyZtc1YksVmrRlchgr6FlXuLXqT/9bdRsdixsT1ToPLGZjMv+37+89MlDkeMQh9q/rgZVtI/XlxDQbOOUKqnEp3K1U+maRUAvG5njhDmlGYk/AR6Tme7N7uhzu/VURL2DPYave1fu6hQcrcyQtEbna98aEPvjH0q6RngEV2o2GebUrbk5nIYS3/qwTrn811BkF7CjHgixkOdJpb5QjY+m8pyg+5IVW2Iaj8KuO4bShOVNQZCj1YvQD+xxeE/iEoOcT6Py1ctf9JC8BERl8UTiIcii1QxVmEsE2855nRqyj1yBpQbBWhwG8qvx89J7e5n8S8u0hvcHwvwh33XIHoDXc7cFHRmr36BJyN7RCJFxMeDP7anxvctb1dAO+cyhtUeBsQ50oOsHMneK1bMN8Cq3a/3mCprxXls+IOOgRolFB+1KurCrieFsGb3I3x5BEpuRpeQAkbENTJi1zZnCgg22UOW2pN01ioCA+I/lSr+lN2Ldq6qgu9hXcv4V7jonX1n/PQ9cZIeFO/CPF4WEJIQBy/vu5ub4Cpo6g7WCIFWOawz++clJPQ3sSusYzeMXxzASQIVzXQJ0skRPRAGaOLKg2cwwxhKf4HXIoCX7LZ65Y1Ndqcp+Y8qOnuUWC7/TP4aqRr84K2xfgnEk3CJk0CkyIY7tK2LspU3m1yyOs3BoVhZG44IHMSWQkSyvxYJXmZXnfqrl+7MNg8W2JEeIfWCyo3z+NiUw9WXWxhlK76M0NKsrUDkfKyOEOE8XNgCtBZJmxubWHiAEK8m56kXXY2xOpSWKReW+eTjgBFSS3UMbaeNkSv1HwlKxSOWTlYCoW/Br/oeK2BwPZYwS/+K5oTEwsdjuoFH3ci2Wtyg+GnRlLGWkfYMwPT5u4GSOdXzRScf2103+gqf/mXNUr4CFu2g9JETRrf1dsRHESXgVBtgZ5HZ/Gy2XAPu5m2w6pPlPmqi96op0H65aabKuTP2mrF0We3GzZ3XQ/888T2iyyqAXZkRnJ4Yu6K3D//sxp07gDAbEVN0pTHhBR+8yaws8liOI/Z2xk5EEOEClZM4exF+aDNPH578zcPMBUlTr6Hsnek09hY07OMbmyr9DpwDKShTAmn1AVMo/8GuX7urMKgbb1n6pMZ270KJyqbvbaeMGPsPo6iaXORE8iaqk+DB/xirElAqyJa6Mzlm9+oNqXvmpFMpstpcGdgVro8SFK6g==
  template:
    metadata:
      creationTimestamp: null
      name: garage-config
      namespace: garage
