apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picoshare-data
  namespace: picoshare
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
