---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: picoshare-env
  namespace: picoshare
spec:
  encryptedData:
    PS_SHARED_SECRET: AgAALA2UblejwB3uS8n3qTr8kRPIEQRdloFW50ccZ/Nyh5NsgbDTXbl4h/4QLuLqLPX5MUCLW9wC8qhu5f0erFTNVhYtdoq1pZ5YYskd1bKFYBA7qAV6+3Hffi+H+Eu6/DV0VgvWeq2wLhETu2d0sMrWcXX0pS60yXXBFijqA9I56F/OCod3xMw2H1mploIEgAQwBAjY0doMm3DMH5PgABHmk3Dq+A0/oWuTP6W+igcv/Z6CxfKjQx3vNHEDMA8ioPvV18g/vuFKAW3NLOOVi8PRCRgH9GNLR8NqluP++OwlVKMdTs1uhNFmIxhC19E/uqaEL4T/EvN0f6W/tYbxzBePbmrNEc+ENFOR4NziYbOBJXE7a4M4YIp9V/mIWmSI2zq9zQlskcx3Hsa3lULcSjXvIYXYkYBMKoNifpbZlz78FB0CKcCjgH+2L5M7rdwI6FPVpGoAZxtLZ9XqTPahSk7G5obYl227jjU+jltW28Mdo6dwooTr0C+rnQLCZgsjg0h2wmcln49r2Cs4vsNKCUOshi07lkz5C/g2eEv9tm7BNectE/TyKuudYWqSar3E2sTCfwGbOagwc3NpTOS2Hikgysq2MpQ3Mn2ONIMXjfWwGuoQFDDoxNsIIqnUHCEZfk2LEWUGJqrG1hR1ms0i6Ge44QoCgaEtjWOxr9lmRrZc2JprcsJJ1rQeh8rDp7wc3FZbtCAySNPoSLWDgbhavBKYuNYTVm6r8rcXkBE22iSDJ57DTcwxY7sEgvAVyA==
  template:
    metadata:
      name: picoshare-env
      namespace: picoshare
