apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman
  namespace: spoolman
spec:
  selector:
    matchLabels:
      app: spoolman
      namespace: spoolman
  template:
    metadata:
      labels:
        app: spoolman
        namespace: spoolman
    spec:
      containers:
      - name: spoolman
        image: ghcr.io/donkie/spoolman:latest
        envFrom:
         - secretRef:
            name: spoolman
            optional: false
        env:
        - name: TZ
          value: "Europe/Warsaw"
        - name: SPOOLMAN_DB_TYPE
          value: "postgres"
        - name: SPOOLMAN_DB_HOST
          value: postgres.postgres
        - name: SPOOLMAN_DB_PORT
          value: "5432"
        - name: SPOOLMAN_HOST
          value: "0.0.0.0"
        - name: SPOOLMAN_PORT
          value: "7912"
---
apiVersion: v1
kind: Service
metadata:
  name: spoolman
  namespace: spoolman
spec:
  selector:
    app: spoolman
  ports:
  - port: 7912
    targetPort: 7912
    name: web
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolman
  namespace: spoolman
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: spoolman.ugard.mywire.org
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: spoolman
              port:
                number: 7912
  tls:
  - hosts:
    - spoolman.ugard.mywire.org
    secretName: tls-spoolman-ingress-http