apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 10.0.10
    helm:
      release-name: velero
      valuesObject:
        metrics:
          enabled: true
          scrapeInterval: 120s
          scrapeTimeout: 10s
          serviceMonitor:
            enabled: true
          nodeAgentPodMonitor:
            enabled: true
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.12.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        ##
        ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
        ## and additional server settings.
        ##
        configuration:
          features: EnableCSI
          deployNodeAgent: true
          # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
          # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
          backupStorageLocation:
            # name is the name of the backup storage location where backups should be stored. If a name is not provided,
            # a backup storage location will be created with the name "default". Optional.
          - name: garage
            # provider is the name for the backup storage location provider.
            provider: "aws"
            # bucket is the name of the bucket to store backups in. Required.
            bucket: "velero-backup"
            # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
            # caCert:
            # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
            # prefix:
            # default indicates this location is the default backup storage location. Optional.
            default: true
            # validationFrequency defines how frequently Velero should validate the object storage. Optional.
            # validationFrequency:
            # accessMode determines if velero can write to this backup storage location. Optional.
            # default to ReadWrite, ReadOnly is used during migrations and restores.
            accessMode: ReadWrite
            credential:
              # name of the secret used by this backupStorageLocation.
              name: velero-s3-secret
              # name of key that contains the secret data to be used.
              key: garage
            # Additional provider-specific configuration. See link above
            # for details of required/optional fields for your provider.
            config:
              region: garage
              s3ForcePathStyle: true
              s3Url: http://garage.garage:3900
          - name: scaleway
            provider: "aws"
            bucket: "lkrzyzak-velero-backup"
            default: false
            accessMode: ReadWrite
            credential:
              name: velero-s3-secret
              key: scaleway
            config:
              region: pl-waw
              s3ForcePathStyle: true
              s3Url: https://s3.pl-waw.scw.cloud
            annotations: {}

          # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
          # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
          volumeSnapshotLocation:
          #   # name is the name of the volume snapshot location where snapshots are being taken. If a name is not provided,
          #   # a volume snapshot location will be created with the name "default". Optional.
            - name: default
          #   # provider is the name for the volume snapshot provider.
              provider: "csi"
          #   credential:
          #     # name of the secret used by this volumeSnapshotLocation.
          #     name:
          #     # name of key that contains the secret data to be used.
          #     key:
          #   # Additional provider-specific configuration. See link above
          #   # for details of required/optional fields for your provider.
          #   config: {}
          #    region:
          #    apiTimeout:
          #    resourceGroup:
          #    The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
          #    subscriptionId:
          #    incremental:
          #    snapshotLocation:
          #    project:

            # annotations allows adding arbitrary annotations to this VolumeSnapshotLocation resource. Optional.
            # annotations: {}
