apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
    helm:
      releaseName: metallb
      valuesObject:
        speaker:
          frr:
            enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
