apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
spec:
  destination:
    namespace: garage
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: garage
    repoURL: http://gitea-web.gitea/api/packages/lkrzyzak/helm 
    targetRevision: 0.7.0
    helm:
      release-name: garage 
      valuesObject:
        garage:
          # Use only 2 replicas per object
          replicationMode: "1"

          # Start 4 instances (StatefulSets) of garage
          deployment:
            replicaCount: 1

          # Override default storage class and size
          persistence:
            meta:
              storageClass: "rook-ceph-block"
              size: 100Mi
            data:
              storageClass: "openebs-zfspv"
              size: 1Gi

          ingress:
            s3:
              api:
                enabled: true
                className: "kustomize-traefik"
                annotations:
                  cert-manager.io/cluster-issuer: "letsencrypt"
                hosts:
                  - host: garage.ugard.mywire.org
                    paths:
                      - path: /
                        pathType: Prefix
                tls:
                  - secretName: garage-ingress-cert
                    hosts:
                      - garage.ugard.mywire.org
                  