apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: cloudflared
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: cloudflared
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 2.2.4
    helm:
      releaseName: cloudflared
      valuesObject:
        replica:
          count: 1
        tunnelConfig:
          name: "manyfold-tunnel"
          logLevel: "info"
        tunnelSecrets:
          existingConfigJsonFileSecret:
            name: cloudflared-config-json
          existingPemFileSecret:
            name: cloudflared-cert-pem
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"