apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-helm
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.3.2
    helm:
      release-name: openebs
      valuesObject:
        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: true
          replicated:
            mayastor:
              enabled: false
        loki:
          enabled: false
        serviceMonitor:
          enabled: true
        