apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-helm
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.4.0
    helm:
      release-name: openebs
      valuesObject:
        alloy:
          enabled: false
        legacy:
          enabled: false
        apiserver:
          enabled: false
        provisioner:
          enabled: false
        localprovisioner:
          enabled: false
        ndm:
          enabled: false
        ndmOperator:
          enabled: false
        webhook:
          enabled: false
        snapshotOperator:
          enabled: false
        localpv:
          enabled: false
        zfs-localpv:
          enabled: true
          zfsNode:
            encrKeysDir: "/var/openebs/keys"
            nodeSelector:
              openebs.io/zfs: "true"
        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: true
          replicated:
            mayastor:
              enabled: false
        loki:
          enabled: false
        serviceMonitor:
          enabled: true
        