apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.1.0
      helm:
        release-name: jellyfin
        valuesObject:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt"
            hosts:
              - host: jellyfin.ugard.mywire.org
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: tls-jellyfin-ingress-http
                hosts:
                  - jellyfin.ugard.mywire.org
          persistence:
            media:
              enabled: false
          volumes:
            - name: bajki
              persistentVolumeClaim:
                claimName: wyse-bajki-pvc
            - name: movies
              persistentVolumeClaim:
                claimName: wyse-movies-pvc
            - name: przyroda
              persistentVolumeClaim:
                claimName: wyse-przyroda-pvc

          # -- Additional volume mounts for the Jellyfin container.
          volumeMounts:
            - name: bajki
              mountPath: /media/bajki
              readOnly: True
            - name: movies
              mountPath: /media/movies
              readOnly: True
            - name: przyroda
              mountPath: /media/przyroda
              readOnly: True
    - path: apps/jellyfin
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}