apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-gitea-actions-runner
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/gitea-actions-runner
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
