apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-benji
  namespace: argocd
spec:
  destination:
    namespace: backup-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/benji-backup
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}