apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-immich-dr
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/immich
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}