apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-hass
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: apps/hass
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
    - chart: zigbee2mqtt
      repoURL: https://charts.zigbee2mqtt.io
      targetRevision: 1.37.1
      helm:
        release-name: zigbee2mqtt
        valuesObject:
          version: 4
          mqtt:
              base_topic: zigbee2mqtt
              server: mqtt://mosquitto-mqtt:1883
          serial:
              port: tcp://192.168.100.122:6638
              baudrate: 115200
              adapter: ember
          advanced:
              channel: 11
              network_key: GENERATE
              pan_id: GENERATE
              ext_pan_id: GENERATE
              transmit_power: 20
          frontend:
              enabled: true
          homeassistant:
              enabled: true
