apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manyfold
  namespace: argocd
spec:
  destination:
    namespace: manyfold
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/manyfold
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}