apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.10.3
    helm:
      release-name: immich
      valueFiles:
      - $values/apps/immich/values.yaml
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    ref: values
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/immich
