apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-kiosk
  namespace: argocd
spec:
  destination:
    namespace: immich-kiosk
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/immich-kiosk/argo-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
