apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.1.2
    helm:
      release-name: traefik
      valuesObject:
        service:
        annotations:
          tailscale.com/expose: "true"
        spec:
          loadBalancerIP: 192.168.10.253