apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.3.0
      helm:
        release-name: jellyfin
        valueFiles:
          - $values/apps/jellyfin/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: apps/jellyfin