apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flashweb
  namespace: argocd
spec:
  destination:
    namespace: flashweb
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/flashweb
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}