apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.1.0
      helm:
        release-name: jellyfin
        valuesObject:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt"
            hosts:
              - host: jellyfin.ugard.mywire.org
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: tls-jellyfin-ingress-http
                hosts:
                  - jellyfin.ugard.mywire.org
          service:
            type: LoadBalancer
          persistence:
            media:
              # -- set to false to use emptyDir
              enabled: true
              accessMode: ReadWriteOnce
              size: 500Gi
              # -- Custom annotations to be added to the PVC
              annotations: {}
              # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
              storageClass: 'openebs-zfspv'
    # - path: apps/jellyfin
    #   repoURL: {{ .Values.spec.source.repoURL }}
    #   targetRevision: {{ .Values.spec.source.targetRevision }}