apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
spec:
  destination:
    namespace: node-red
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - chart: node-red
    repoURL: https://schwarzit.github.io/node-red-chart/
    targetRevision: 0.33.0
    helm:
      release-name: node-red
      valueFiles:
      - $values/apps/node-red/values.yaml
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    ref: values