apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appflowy
  namespace: argocd
spec:
  destination:
    namespace: appflowy
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/appflowy
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}