apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-hass
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: apps/hass
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
    - chart: zigbee2mqtt
      repoURL: https://charts.zigbee2mqtt.io
      targetRevision: 2.6.3
      helm:
        release-name: zigbee2mqtt
        valuesObject:
          statefulset:
            securityContext:
              capabilities:
                add: []
                drop:
                  - ALL
              privileged: false
              runAsNonRoot: false
              runAsUser: 0
          zigbee2mqtt:
            advanced:
              channel: 24
              ext_pan_id: GENERATE
              network_key: GENERATE
              pan_id: GENERATE
              transmit_power: 20
            frontend:
              enabled: true
            homeassistant:
              enabled: true
            mqtt:
              base_topic: zigbee2mqtt
              server: mqtt://mosquitto-mqtt:1883
            serial:
              adapter: ember
              baudrate: 115200
              port: tcp://192.168.100.122:6638
            version: 4
