apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-hass
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: apps/hass
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
    - chart: zigbee2mqtt
      repoURL: https://charts.zigbee2mqtt.io
      targetRevision: 2.6.3
      helm:
        release-name: zigbee2mqtt
        valuesObject:
          statefulset:
            securityContext:
              capabilities:
                add: []
                drop:
                  - ALL
              privileged: false
              runAsNonRoot: false
              runAsUser: 0
          zigbee2mqtt:
            advanced:
              channel: 24
              pan_id: 6754                       # 16‑bit PAN ID (decimal, avoid 0 and 65535)
              ext_pan_id: [94, 172, 147, 18, 71, 184, 45, 241]   # 8 bytes (0–255)
              network_key: "A3E48F25B6C10D79F2A18C0B44D65E9C"    # 16‑byte key as 32 hex chars
              transmit_power: 20
            frontend:
              enabled: true
            homeassistant:
              enabled: true
            mqtt:
              base_topic: zigbee2mqtt
              server: mqtt://mosquitto-mqtt:1883
            serial:
              adapter: ember
              baudrate: 115200
              port: tcp://192.168.100.122:6638
            version: 4
            external_converters:
              - TS0601_TZE200_6rdj8dzm.js
          extraVolumes:
            - name: zigbee-converter
              configMap:
                name: zigbee-converter-configmap
          extraVolumeMounts:
            - name: zigbee-converter
              mountPath: /app/data/TS0601_TZE200_6rdj8dzm.js
              subPath: TS0601_TZE200_6rdj8dzm.js
