apiVersion: batch/v1
kind: Job
metadata:
  name: zot-registry-data-migration
  namespace: registry
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting data migration from zot-registry-pvc to zot-registry-pvc-zot-registry-0"
          
          # Mount points
          OLD_DATA="/old-data"
          NEW_DATA="/new-data"
          
          # Check if old data exists
          if [ ! -d "$OLD_DATA" ]; then
            echo "Error: Old data directory not found"
            exit 1
          fi
          
          # Check if new data directory exists
          if [ ! -d "$NEW_DATA" ]; then
            echo "Creating new data directory"
            mkdir -p "$NEW_DATA"
          fi
          
          # Copy data with progress
          echo "Copying data from $OLD_DATA to $NEW_DATA"
          cp -av "$OLD_DATA/"* "$NEW_DATA/" 2>&1
          
          # Verify copy
          echo "Verifying copied data..."
          if [ -f "$NEW_DATA/.git" ]; then
            echo "Git repository found in new location"
          fi
          
          # List contents
          echo "New data directory contents:"
          ls -la "$NEW_DATA"
          
          echo "Data migration completed successfully"
        volumeMounts:
        - name: old-pvc
          mountPath: /old-data
        - name: new-pvc
          mountPath: /new-data
      volumes:
      - name: old-pvc
        persistentVolumeClaim:
          claimName: zot-registry-pvc
      - name: new-pvc
        persistentVolumeClaim:
          claimName: zot-registry-pvc-zot-registry-0
  backoffLimit: 3