apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  ports:
  - name: http
    port: 8384
    protocol: TCP
  - name: tcp-ft
    port: 22000
    protocol: TCP
  - name: quic-ft
    port: 22000
    protocol: UDP
  - name: local-discovery
    port: 21027
    protocol: UDP
  selector:
    app: syncthing
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      # hostNetwork: true
      containers:
      - image: docker.io/syncthing/syncthing:latest
        name: syncthing
        ports:
        - name: http
          containerPort: 8384
          protocol: TCP
        - name: tcp-ft
          containerPort: 22000
          protocol: TCP
        - name: quic-ft
          containerPort: 22000
          protocol: UDP
        - name: local-discovery
          containerPort: 21027
          protocol: UDP
        readinessProbe:
          tcpSocket:
            port: 8384
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8384
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
          - name: syncthing-data
            mountPath: /var/syncthing
      volumes:
        - name: syncthing-data
          persistentVolumeClaim:
            claimName: syncthing-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  namespace: syncthing
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: syncthing.ugard.mywire.org
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: syncthing
              port:
                number: 8384
  tls:
  - hosts:
    - syncthing.ugard.mywire.org
    secretName: tls-syncthing-ingress-http
