apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 66G
  storageClassName: openebs-zfspv