---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alert-webhook-mqtt
  namespace: monitoring
spec:
  encryptedData:
    MQTT_PASSWORD: AgAd2nLYIJ3IUUbDERulZiqWwbwiE4XXwT3CfF6rizDSeBUdBy3R/WExbaADXQwp6Qdf5UxsQ4R/nTjXY4Dc1dnJ64WASLVB2YNlW6Ma5CtAUDLU45lmyFIJF/HDt1go2suOIGSlM8PCTEuGpRbRi52xmYO6VPga/PQEZmn0Q+HOKC/Bhr1CUDSLW8q0kKUFcRmg8jeGGyBBirocBqnrv/cK1CFxu5VbX9tgz/xFRmX2pg7L/T7jBdgDaZOLTM/gNq909LGQ5UT6eE1OA4X2DpY/097h/TWs5pCppP0dRSKXwvVv2oCTB5FfvxQYsuOlLj/gZhUkKNe+I4Tx+J7PrYV+TVVvHXpI+gqIC8JpiMlTtTUxovMimH1ZznNhWXa3bARCv6x5ESAEQ49UZ63x90kX/IsC4/dhXPonEZFlVlhs9njBV7AOeAHc6uCMOssMHAeYnYhXhm5C5OhXvL+O6ElwaNBNuLPMMKw1AUrhGI+wkgM4RtYwBx5fa3ZcU3NZb7yZufL44fwJ8tPBNDhslvrPWV5wcWPsq6cgARAjU/5s7NDcsCJjmx120HCK4io8DUS7AwBcu90AM/qN8x1WorudCetYKaudQpVs8/UqGcQDO8lKad+xwhElHnk0CMDsQOaAhB33qqBy9C05yhU5RfjAeQFc5cH0UFa5eU0yD3G802vqYd4BBDIjHx3jol175pJz5XufUhDAMF0hKlCOzgYjCx7JGhQp++0=
  template:
    metadata:
      name: alert-webhook-mqtt
      namespace: monitoring
