---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alert-webhook-healthchecks
  namespace: monitoring
spec:
  encryptedData:
    HEALTHCHECKS_API_KEY: AgC6yxs5ZPr7rfKA7LzBsifyRDX5/YqnOiZfZUzvUwRCuPN7k6SssBB50lDANDQKLqxVZadNSCgJ2+JWai/2hsu/Qhi5fo8gtXBz99jCIKsv2aLhcA9uazIJ7Ft1pRAfWbVLQASEvg17dHzag1B/d/iNAVtzJvz+AfruE1RZ45Q6hlzX9KUAbK+ybcwT/V0CWSn2/qq4Iz0mFp9ctw72X0q1lGoojOLBZM6PqQv568zoWqq823VsbOsShbsPud8b+0B9aaLKijZaILwAGtZQHLtDWrDVGggE4ECneCmovCgGcKKWYpolJpPJrykLWTSR/jI/KHld8+r63t/WSQ3fXOygDa6wFKprGwBmkPj7xvYA0b83H1kbQsSrF5JvLKqDiel803yCiRclW5jxWkI6HhLD5lcNhkB9tSq13kxkKX2dE0bvHE/bW+ryrrN/ziein13TXXLB2uuPK2p3EN0CX9TgsE9mvj1/l95AZxa6r7btoYlHI+ov5zmqA+gVJeof1KYpfg+k6ZTNVcEj5cuRxGUGVdACLVW+7JOWMpZZMTSRRCsEwqJd7PCvex7k8fA7He58TKoii7jJnM2en4KlNziVoiutbliNpcLjtWCN/wu6qDGgNyIqD9DQo+yfab20A4ltsPQlGQfItxQzJI2dBfg/kjy/19KXAEweq9Hvk1GBUsQuSlAlAkKBFtLx4pXnCYD1fwEetRo9ACZjYJdzpgflpW37yccpwpqezJpzLq70SQ==
  template:
    metadata:
      name: alert-webhook-healthchecks
      namespace: monitoring
