apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-ceph
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
